### ISSUE TITLE
[FEAT]User model to the table according to the following schema

### ISSUE THREAD

**Issue by cool-pants** [ComputerSocietyVITC/Sahaay#6]
The user model should contain the following parameters as columns in the table:
- User ID(made from a mix of their regno and work/job)(Primary Key)
- Registration number(Required and unique key, many company use cases wont have this for their workers)

Abstract the following
- [ ] User Name 
- [ ] First Name and Last Name
- [ ] E-mail

**Comment by AbhijithGanesh** [comment]
This can be closed as Django User model establishes a table for us

**Comment by AbhijithGanesh** [comment]
I don't think you need to mention the settings realated to password, also we need foreign key map to User object in django

**Comment by AbhijithGanesh** [comment]
It's a foreign object mapping, we're not doing a one to one map so it must work well, we're mapping the whole user object so it should work perfectly

**Comment by cool-pants** [comment]
Well I know of User Abstraction but I believe we don't necessarily have a need for the Profile and Profile Manager Classes, so we need to make the User class more suited to our Purpose, we could just use the UserManager class from ``auth.models``
